/**
 * @file hce.h
 *
 * @brief This header file was generated by cantools version 40.5.0 Fri Mar 27 15:50:23 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef HCE_H
#define HCE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define HCE_HCE_ALT_RADAR_REPORT_FRAME_ID (0x11000u)
#define HCE_HCE_EMU_REPORT_FRAME_ID (0x12000u)
#define HCE_HCE_SSDM_CYCLIC_X_REPORT_FRAME_ID (0x20000u)
#define HCE_HCE_SSDM_CYCLIC_X_SET_POSITION_FRAME_ID (0x20006u)
#define HCE_HCE_SSDM_CYCLIC_Y_REPORT_FRAME_ID (0x21000u)
#define HCE_HCE_SSDM_CYCLIC_Y_SET_POSITION_FRAME_ID (0x21006u)
#define HCE_HCE_SSDM_COLLECTIVE_REPORT_FRAME_ID (0x22000u)
#define HCE_HCE_SSDM_COLLECTIVE_SET_POSITION_FRAME_ID (0x22006u)
#define HCE_HCE_SSDM_RUDDER_REPORT_FRAME_ID (0x23000u)
#define HCE_HCE_SSDM_RUDDER_SET_POSITION_FRAME_ID (0x23006u)
#define HCE_HCE_SSDM_THROTTLE_REPORT_FRAME_ID (0x24000u)
#define HCE_HCE_SSDM_THROTTLE_SET_POSITION_FRAME_ID (0x24006u)
#define HCE_HCE_SSDM_AUXILIARY_REPORT_FRAME_ID (0x25000u)
#define HCE_HCE_SSDM_AUXILIARY_SET_POSITION_FRAME_ID (0x25006u)

/* Frame lengths in bytes. */
#define HCE_HCE_ALT_RADAR_REPORT_LENGTH (2u)
#define HCE_HCE_EMU_REPORT_LENGTH (8u)
#define HCE_HCE_SSDM_CYCLIC_X_REPORT_LENGTH (8u)
#define HCE_HCE_SSDM_CYCLIC_X_SET_POSITION_LENGTH (2u)
#define HCE_HCE_SSDM_CYCLIC_Y_REPORT_LENGTH (8u)
#define HCE_HCE_SSDM_CYCLIC_Y_SET_POSITION_LENGTH (2u)
#define HCE_HCE_SSDM_COLLECTIVE_REPORT_LENGTH (8u)
#define HCE_HCE_SSDM_COLLECTIVE_SET_POSITION_LENGTH (2u)
#define HCE_HCE_SSDM_RUDDER_REPORT_LENGTH (8u)
#define HCE_HCE_SSDM_RUDDER_SET_POSITION_LENGTH (2u)
#define HCE_HCE_SSDM_THROTTLE_REPORT_LENGTH (8u)
#define HCE_HCE_SSDM_THROTTLE_SET_POSITION_LENGTH (2u)
#define HCE_HCE_SSDM_AUXILIARY_REPORT_LENGTH (8u)
#define HCE_HCE_SSDM_AUXILIARY_SET_POSITION_LENGTH (2u)

/* Extended or standard frame types. */
#define HCE_HCE_ALT_RADAR_REPORT_IS_EXTENDED (1)
#define HCE_HCE_EMU_REPORT_IS_EXTENDED (1)
#define HCE_HCE_SSDM_CYCLIC_X_REPORT_IS_EXTENDED (1)
#define HCE_HCE_SSDM_CYCLIC_X_SET_POSITION_IS_EXTENDED (1)
#define HCE_HCE_SSDM_CYCLIC_Y_REPORT_IS_EXTENDED (1)
#define HCE_HCE_SSDM_CYCLIC_Y_SET_POSITION_IS_EXTENDED (1)
#define HCE_HCE_SSDM_COLLECTIVE_REPORT_IS_EXTENDED (1)
#define HCE_HCE_SSDM_COLLECTIVE_SET_POSITION_IS_EXTENDED (1)
#define HCE_HCE_SSDM_RUDDER_REPORT_IS_EXTENDED (1)
#define HCE_HCE_SSDM_RUDDER_SET_POSITION_IS_EXTENDED (1)
#define HCE_HCE_SSDM_THROTTLE_REPORT_IS_EXTENDED (1)
#define HCE_HCE_SSDM_THROTTLE_SET_POSITION_IS_EXTENDED (1)
#define HCE_HCE_SSDM_AUXILIARY_REPORT_IS_EXTENDED (1)
#define HCE_HCE_SSDM_AUXILIARY_SET_POSITION_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define HCE_HCE_ALT_RADAR_REPORT_NAME "HCE_AltRadar_Report"
#define HCE_HCE_EMU_REPORT_NAME "HCE_EMU_Report"
#define HCE_HCE_SSDM_CYCLIC_X_REPORT_NAME "HCE_SSDM_CyclicX_Report"
#define HCE_HCE_SSDM_CYCLIC_X_SET_POSITION_NAME "HCE_SSDM_CyclicX_SetPosition"
#define HCE_HCE_SSDM_CYCLIC_Y_REPORT_NAME "HCE_SSDM_CyclicY_Report"
#define HCE_HCE_SSDM_CYCLIC_Y_SET_POSITION_NAME "HCE_SSDM_CyclicY_SetPosition"
#define HCE_HCE_SSDM_COLLECTIVE_REPORT_NAME "HCE_SSDM_Collective_Report"
#define HCE_HCE_SSDM_COLLECTIVE_SET_POSITION_NAME "HCE_SSDM_Collective_SetPosition"
#define HCE_HCE_SSDM_RUDDER_REPORT_NAME "HCE_SSDM_Rudder_Report"
#define HCE_HCE_SSDM_RUDDER_SET_POSITION_NAME "HCE_SSDM_Rudder_SetPosition"
#define HCE_HCE_SSDM_THROTTLE_REPORT_NAME "HCE_SSDM_Throttle_Report"
#define HCE_HCE_SSDM_THROTTLE_SET_POSITION_NAME "HCE_SSDM_Throttle_SetPosition"
#define HCE_HCE_SSDM_AUXILIARY_REPORT_NAME "HCE_SSDM_Auxiliary_Report"
#define HCE_HCE_SSDM_AUXILIARY_SET_POSITION_NAME "HCE_SSDM_Auxiliary_SetPosition"

/* Signal Names. */
#define HCE_HCE_ALT_RADAR_REPORT_AGL_NAME "AGL"
#define HCE_HCE_EMU_REPORT_VBATT_NAME "Vbatt"
#define HCE_HCE_EMU_REPORT_ICURRENT_NAME "Icurrent"
#define HCE_HCE_EMU_REPORT_ROTOR_RPM_NAME "RotorRPM"
#define HCE_HCE_EMU_REPORT_MOTOR_RPM_NAME "MotorRPM"
#define HCE_HCE_EMU_REPORT_EGT_NAME "EGT"
#define HCE_HCE_SSDM_CYCLIC_X_REPORT_POSITION_NAME "Position"
#define HCE_HCE_SSDM_CYCLIC_X_SET_POSITION_SETPOINT_NAME "Setpoint"
#define HCE_HCE_SSDM_CYCLIC_Y_REPORT_POSITION_NAME "Position"
#define HCE_HCE_SSDM_CYCLIC_Y_SET_POSITION_SETPOINT_NAME "Setpoint"
#define HCE_HCE_SSDM_COLLECTIVE_REPORT_POSITION_NAME "Position"
#define HCE_HCE_SSDM_COLLECTIVE_SET_POSITION_SETPOINT_NAME "Setpoint"
#define HCE_HCE_SSDM_RUDDER_REPORT_POSITION_NAME "Position"
#define HCE_HCE_SSDM_RUDDER_SET_POSITION_SETPOINT_NAME "Setpoint"
#define HCE_HCE_SSDM_THROTTLE_REPORT_POSITION_NAME "Position"
#define HCE_HCE_SSDM_THROTTLE_SET_POSITION_SETPOINT_NAME "Setpoint"
#define HCE_HCE_SSDM_AUXILIARY_REPORT_POSITION_NAME "Position"
#define HCE_HCE_SSDM_AUXILIARY_SET_POSITION_SETPOINT_NAME "Setpoint"

/**
 * Signals in message HCE_AltRadar_Report.
 *
 * Altitude Radar Report Message
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_alt_radar_report_t {
    /**
     * Range: 0..65535 (0..655.35 m)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t agl;
};

/**
 * Signals in message HCE_EMU_Report.
 *
 * Engine Monitoring Unit Report Message (Truncated to 8 bytes)
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_emu_report_t {
    /**
     * Range: 0..255 (0..25.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t vbatt;

    /**
     * Range: -128..127 (-128..127 A)
     * Scale: 1
     * Offset: 0
     */
    int8_t icurrent;

    /**
     * Range: 0..65535 (0..65535 RPM)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rotor_rpm;

    /**
     * Range: 0..65535 (0..65535 RPM)
     * Scale: 1
     * Offset: 0
     */
    uint16_t motor_rpm;

    /**
     * Range: 0..65535 (0..65535 C)
     * Scale: 1
     * Offset: 0
     */
    uint16_t egt;
};

/**
 * Signals in message HCE_SSDM_CyclicX_Report.
 *
 * Servo Feedback: Cyclic X Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_cyclic_x_report_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t position;
};

/**
 * Signals in message HCE_SSDM_CyclicX_SetPosition.
 *
 * Servo Command: Set Cyclic X Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_cyclic_x_set_position_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t setpoint;
};

/**
 * Signals in message HCE_SSDM_CyclicY_Report.
 *
 * Servo Feedback: Cyclic Y Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_cyclic_y_report_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t position;
};

/**
 * Signals in message HCE_SSDM_CyclicY_SetPosition.
 *
 * Servo Command: Set Cyclic Y Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_cyclic_y_set_position_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t setpoint;
};

/**
 * Signals in message HCE_SSDM_Collective_Report.
 *
 * Servo Feedback: Collective Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_collective_report_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t position;
};

/**
 * Signals in message HCE_SSDM_Collective_SetPosition.
 *
 * Servo Command: Set Collective Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_collective_set_position_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t setpoint;
};

/**
 * Signals in message HCE_SSDM_Rudder_Report.
 *
 * Servo Feedback: Rudder Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_rudder_report_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t position;
};

/**
 * Signals in message HCE_SSDM_Rudder_SetPosition.
 *
 * Servo Command: Set Rudder Position
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_rudder_set_position_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t setpoint;
};

/**
 * Signals in message HCE_SSDM_Throttle_Report.
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_throttle_report_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t position;
};

/**
 * Signals in message HCE_SSDM_Throttle_SetPosition.
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_throttle_set_position_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t setpoint;
};

/**
 * Signals in message HCE_SSDM_Auxiliary_Report.
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_auxiliary_report_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t position;
};

/**
 * Signals in message HCE_SSDM_Auxiliary_SetPosition.
 *
 * All signal values are as on the CAN bus.
 */
struct hce_hce_ssdm_auxiliary_set_position_t {
    /**
     * Range: -32768..32768 (-1..1 -)
     * Scale: 3.0517578125e-05
     * Offset: 0
     */
    int16_t setpoint;
};

/**
 * Pack message HCE_AltRadar_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_alt_radar_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_alt_radar_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_AltRadar_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_alt_radar_report_unpack(
    struct hce_hce_alt_radar_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_AltRadar_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_alt_radar_report_init(struct hce_hce_alt_radar_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t hce_hce_alt_radar_report_agl_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_alt_radar_report_agl_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_alt_radar_report_agl_is_in_range(uint16_t value);

/**
 * Pack message HCE_EMU_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_emu_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_emu_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_EMU_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_emu_report_unpack(
    struct hce_hce_emu_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_EMU_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_emu_report_init(struct hce_hce_emu_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t hce_hce_emu_report_vbatt_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_emu_report_vbatt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_emu_report_vbatt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t hce_hce_emu_report_icurrent_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_emu_report_icurrent_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_emu_report_icurrent_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t hce_hce_emu_report_rotor_rpm_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_emu_report_rotor_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_emu_report_rotor_rpm_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t hce_hce_emu_report_motor_rpm_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_emu_report_motor_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_emu_report_motor_rpm_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t hce_hce_emu_report_egt_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_emu_report_egt_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_emu_report_egt_is_in_range(uint16_t value);

/**
 * Pack message HCE_SSDM_CyclicX_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_cyclic_x_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_x_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_CyclicX_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_cyclic_x_report_unpack(
    struct hce_hce_ssdm_cyclic_x_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_CyclicX_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_cyclic_x_report_init(struct hce_hce_ssdm_cyclic_x_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_cyclic_x_report_position_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_cyclic_x_report_position_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_cyclic_x_report_position_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_CyclicX_SetPosition.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_cyclic_x_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_x_set_position_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_CyclicX_SetPosition.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_cyclic_x_set_position_unpack(
    struct hce_hce_ssdm_cyclic_x_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_CyclicX_SetPosition.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_cyclic_x_set_position_init(struct hce_hce_ssdm_cyclic_x_set_position_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_cyclic_x_set_position_setpoint_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_cyclic_x_set_position_setpoint_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_cyclic_x_set_position_setpoint_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_CyclicY_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_cyclic_y_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_y_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_CyclicY_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_cyclic_y_report_unpack(
    struct hce_hce_ssdm_cyclic_y_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_CyclicY_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_cyclic_y_report_init(struct hce_hce_ssdm_cyclic_y_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_cyclic_y_report_position_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_cyclic_y_report_position_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_cyclic_y_report_position_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_CyclicY_SetPosition.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_cyclic_y_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_y_set_position_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_CyclicY_SetPosition.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_cyclic_y_set_position_unpack(
    struct hce_hce_ssdm_cyclic_y_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_CyclicY_SetPosition.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_cyclic_y_set_position_init(struct hce_hce_ssdm_cyclic_y_set_position_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_cyclic_y_set_position_setpoint_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_cyclic_y_set_position_setpoint_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_cyclic_y_set_position_setpoint_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Collective_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_collective_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_collective_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Collective_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_collective_report_unpack(
    struct hce_hce_ssdm_collective_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Collective_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_collective_report_init(struct hce_hce_ssdm_collective_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_collective_report_position_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_collective_report_position_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_collective_report_position_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Collective_SetPosition.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_collective_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_collective_set_position_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Collective_SetPosition.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_collective_set_position_unpack(
    struct hce_hce_ssdm_collective_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Collective_SetPosition.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_collective_set_position_init(struct hce_hce_ssdm_collective_set_position_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_collective_set_position_setpoint_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_collective_set_position_setpoint_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_collective_set_position_setpoint_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Rudder_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_rudder_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_rudder_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Rudder_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_rudder_report_unpack(
    struct hce_hce_ssdm_rudder_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Rudder_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_rudder_report_init(struct hce_hce_ssdm_rudder_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_rudder_report_position_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_rudder_report_position_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_rudder_report_position_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Rudder_SetPosition.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_rudder_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_rudder_set_position_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Rudder_SetPosition.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_rudder_set_position_unpack(
    struct hce_hce_ssdm_rudder_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Rudder_SetPosition.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_rudder_set_position_init(struct hce_hce_ssdm_rudder_set_position_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_rudder_set_position_setpoint_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_rudder_set_position_setpoint_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_rudder_set_position_setpoint_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Throttle_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_throttle_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_throttle_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Throttle_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_throttle_report_unpack(
    struct hce_hce_ssdm_throttle_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Throttle_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_throttle_report_init(struct hce_hce_ssdm_throttle_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_throttle_report_position_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_throttle_report_position_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_throttle_report_position_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Throttle_SetPosition.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_throttle_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_throttle_set_position_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Throttle_SetPosition.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_throttle_set_position_unpack(
    struct hce_hce_ssdm_throttle_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Throttle_SetPosition.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_throttle_set_position_init(struct hce_hce_ssdm_throttle_set_position_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_throttle_set_position_setpoint_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_throttle_set_position_setpoint_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_throttle_set_position_setpoint_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Auxiliary_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_auxiliary_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_auxiliary_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Auxiliary_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_auxiliary_report_unpack(
    struct hce_hce_ssdm_auxiliary_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Auxiliary_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_auxiliary_report_init(struct hce_hce_ssdm_auxiliary_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_auxiliary_report_position_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_auxiliary_report_position_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_auxiliary_report_position_is_in_range(int16_t value);

/**
 * Pack message HCE_SSDM_Auxiliary_SetPosition.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int hce_hce_ssdm_auxiliary_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_auxiliary_set_position_t *src_p,
    size_t size);

/**
 * Unpack message HCE_SSDM_Auxiliary_SetPosition.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int hce_hce_ssdm_auxiliary_set_position_unpack(
    struct hce_hce_ssdm_auxiliary_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_SSDM_Auxiliary_SetPosition.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int hce_hce_ssdm_auxiliary_set_position_init(struct hce_hce_ssdm_auxiliary_set_position_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t hce_hce_ssdm_auxiliary_set_position_setpoint_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float hce_hce_ssdm_auxiliary_set_position_setpoint_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool hce_hce_ssdm_auxiliary_set_position_setpoint_is_in_range(int16_t value);


#ifdef __cplusplus
}
#endif

#endif
