/**
 * @file ahrs.c
 *
 * @brief This source file was generated by cantools version 40.5.0 Fri Mar 27 15:50:15 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "can_ahrs.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int ahrs_hce_ahrs_report_pack(
    uint8_t *dst_p,
    const struct ahrs_hce_ahrs_report_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t ang_vel_pitch;
    uint16_t ang_vel_roll;
    uint16_t ang_vel_yaw;
    uint16_t pitch;
    uint16_t roll;
    uint16_t yaw;
    uint32_t latitude;
    uint32_t longitude;
    uint8_t oat;

    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_left_shift_u8(src_p->system_status, 0u, 0xffu);
    pitch = (uint16_t)src_p->pitch;
    dst_p[1] |= pack_left_shift_u16(pitch, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(pitch, 8u, 0xffu);
    roll = (uint16_t)src_p->roll;
    dst_p[3] |= pack_left_shift_u16(roll, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(roll, 8u, 0xffu);
    yaw = (uint16_t)src_p->yaw;
    dst_p[5] |= pack_left_shift_u16(yaw, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(yaw, 8u, 0xffu);
    accel_x = (uint16_t)src_p->accel_x;
    dst_p[7] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[8] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[9] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[11] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[12] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    ang_vel_pitch = (uint16_t)src_p->ang_vel_pitch;
    dst_p[13] |= pack_left_shift_u16(ang_vel_pitch, 0u, 0xffu);
    dst_p[14] |= pack_right_shift_u16(ang_vel_pitch, 8u, 0xffu);
    ang_vel_roll = (uint16_t)src_p->ang_vel_roll;
    dst_p[15] |= pack_left_shift_u16(ang_vel_roll, 0u, 0xffu);
    dst_p[16] |= pack_right_shift_u16(ang_vel_roll, 8u, 0xffu);
    ang_vel_yaw = (uint16_t)src_p->ang_vel_yaw;
    dst_p[17] |= pack_left_shift_u16(ang_vel_yaw, 0u, 0xffu);
    dst_p[18] |= pack_right_shift_u16(ang_vel_yaw, 8u, 0xffu);
    dst_p[33] |= pack_left_shift_u16(src_p->pressure_altitude, 0u, 0xffu);
    dst_p[34] |= pack_right_shift_u16(src_p->pressure_altitude, 8u, 0xffu);
    oat = (uint8_t)src_p->oat;
    dst_p[37] |= pack_left_shift_u8(oat, 0u, 0xffu);
    memcpy(&latitude, &src_p->latitude, sizeof(latitude));
    dst_p[38] |= pack_left_shift_u32(latitude, 0u, 0xffu);
    dst_p[39] |= pack_right_shift_u32(latitude, 8u, 0xffu);
    dst_p[40] |= pack_right_shift_u32(latitude, 16u, 0xffu);
    dst_p[41] |= pack_right_shift_u32(latitude, 24u, 0xffu);
    memcpy(&longitude, &src_p->longitude, sizeof(longitude));
    dst_p[42] |= pack_left_shift_u32(longitude, 0u, 0xffu);
    dst_p[43] |= pack_right_shift_u32(longitude, 8u, 0xffu);
    dst_p[44] |= pack_right_shift_u32(longitude, 16u, 0xffu);
    dst_p[45] |= pack_right_shift_u32(longitude, 24u, 0xffu);
    dst_p[56] |= pack_left_shift_u8(src_p->num_sat, 0u, 0xffu);
    dst_p[57] |= pack_left_shift_u8(src_p->year, 0u, 0xffu);
    dst_p[58] |= pack_left_shift_u8(src_p->month, 0u, 0xffu);
    dst_p[59] |= pack_left_shift_u8(src_p->day, 0u, 0xffu);
    dst_p[60] |= pack_left_shift_u8(src_p->hour, 0u, 0xffu);
    dst_p[61] |= pack_left_shift_u8(src_p->minute, 0u, 0xffu);
    dst_p[62] |= pack_left_shift_u16(src_p->millisecond, 0u, 0xffu);
    dst_p[63] |= pack_right_shift_u16(src_p->millisecond, 8u, 0xffu);

    return (64);
}

int ahrs_hce_ahrs_report_unpack(
    struct ahrs_hce_ahrs_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t ang_vel_pitch;
    uint16_t ang_vel_roll;
    uint16_t ang_vel_yaw;
    uint16_t pitch;
    uint16_t roll;
    uint16_t yaw;
    uint32_t latitude;
    uint32_t longitude;
    uint8_t oat;

    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->system_status = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    pitch = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    pitch |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->pitch = (int16_t)pitch;
    roll = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    roll |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->roll = (int16_t)roll;
    yaw = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    yaw |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->yaw = (int16_t)yaw;
    accel_x = unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[8], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[9], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[10], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[11], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[12], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    ang_vel_pitch = unpack_right_shift_u16(src_p[13], 0u, 0xffu);
    ang_vel_pitch |= unpack_left_shift_u16(src_p[14], 8u, 0xffu);
    dst_p->ang_vel_pitch = (int16_t)ang_vel_pitch;
    ang_vel_roll = unpack_right_shift_u16(src_p[15], 0u, 0xffu);
    ang_vel_roll |= unpack_left_shift_u16(src_p[16], 8u, 0xffu);
    dst_p->ang_vel_roll = (int16_t)ang_vel_roll;
    ang_vel_yaw = unpack_right_shift_u16(src_p[17], 0u, 0xffu);
    ang_vel_yaw |= unpack_left_shift_u16(src_p[18], 8u, 0xffu);
    dst_p->ang_vel_yaw = (int16_t)ang_vel_yaw;
    dst_p->pressure_altitude = unpack_right_shift_u16(src_p[33], 0u, 0xffu);
    dst_p->pressure_altitude |= unpack_left_shift_u16(src_p[34], 8u, 0xffu);
    oat = unpack_right_shift_u8(src_p[37], 0u, 0xffu);
    dst_p->oat = (int8_t)oat;
    latitude = unpack_right_shift_u32(src_p[38], 0u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[39], 8u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[40], 16u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[41], 24u, 0xffu);
    memcpy(&dst_p->latitude, &latitude, sizeof(dst_p->latitude));
    longitude = unpack_right_shift_u32(src_p[42], 0u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[43], 8u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[44], 16u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[45], 24u, 0xffu);
    memcpy(&dst_p->longitude, &longitude, sizeof(dst_p->longitude));
    dst_p->num_sat = unpack_right_shift_u8(src_p[56], 0u, 0xffu);
    dst_p->year = unpack_right_shift_u8(src_p[57], 0u, 0xffu);
    dst_p->month = unpack_right_shift_u8(src_p[58], 0u, 0xffu);
    dst_p->day = unpack_right_shift_u8(src_p[59], 0u, 0xffu);
    dst_p->hour = unpack_right_shift_u8(src_p[60], 0u, 0xffu);
    dst_p->minute = unpack_right_shift_u8(src_p[61], 0u, 0xffu);
    dst_p->millisecond = unpack_right_shift_u16(src_p[62], 0u, 0xffu);
    dst_p->millisecond |= unpack_left_shift_u16(src_p[63], 8u, 0xffu);

    return (0);
}

int ahrs_hce_ahrs_report_init(struct ahrs_hce_ahrs_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ahrs_hce_ahrs_report_t));

    return 0;
}

uint8_t ahrs_hce_ahrs_report_system_status_encode(float value)
{
    return (uint8_t)(value);
}

float ahrs_hce_ahrs_report_system_status_decode(uint8_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_system_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_pitch_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ahrs_hce_ahrs_report_pitch_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ahrs_hce_ahrs_report_pitch_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_roll_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ahrs_hce_ahrs_report_roll_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ahrs_hce_ahrs_report_roll_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_yaw_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float ahrs_hce_ahrs_report_yaw_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool ahrs_hce_ahrs_report_yaw_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_accel_x_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ahrs_hce_ahrs_report_accel_x_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ahrs_hce_ahrs_report_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_accel_y_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ahrs_hce_ahrs_report_accel_y_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ahrs_hce_ahrs_report_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_accel_z_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ahrs_hce_ahrs_report_accel_z_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ahrs_hce_ahrs_report_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_ang_vel_pitch_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ahrs_hce_ahrs_report_ang_vel_pitch_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ahrs_hce_ahrs_report_ang_vel_pitch_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_ang_vel_roll_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ahrs_hce_ahrs_report_ang_vel_roll_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ahrs_hce_ahrs_report_ang_vel_roll_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ahrs_hce_ahrs_report_ang_vel_yaw_encode(float value)
{
    return (int16_t)(value / 0.001f);
}

float ahrs_hce_ahrs_report_ang_vel_yaw_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool ahrs_hce_ahrs_report_ang_vel_yaw_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t ahrs_hce_ahrs_report_pressure_altitude_encode(float value)
{
    return (uint16_t)(value);
}

float ahrs_hce_ahrs_report_pressure_altitude_decode(uint16_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_pressure_altitude_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int8_t ahrs_hce_ahrs_report_oat_encode(float value)
{
    return (int8_t)(value);
}

float ahrs_hce_ahrs_report_oat_decode(int8_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_oat_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

float ahrs_hce_ahrs_report_latitude_encode(float value)
{
    return (float)(value);
}

float ahrs_hce_ahrs_report_latitude_decode(float value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_latitude_is_in_range(float value)
{
    (void)value;

    return (true);
}

float ahrs_hce_ahrs_report_longitude_encode(float value)
{
    return (float)(value);
}

float ahrs_hce_ahrs_report_longitude_decode(float value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_longitude_is_in_range(float value)
{
    (void)value;

    return (true);
}

uint8_t ahrs_hce_ahrs_report_num_sat_encode(float value)
{
    return (uint8_t)(value);
}

float ahrs_hce_ahrs_report_num_sat_decode(uint8_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_num_sat_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ahrs_hce_ahrs_report_year_encode(float value)
{
    return (uint8_t)(value - 2000.0f);
}

float ahrs_hce_ahrs_report_year_decode(uint8_t value)
{
    return ((float)value + 2000.0f);
}

bool ahrs_hce_ahrs_report_year_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ahrs_hce_ahrs_report_month_encode(float value)
{
    return (uint8_t)(value);
}

float ahrs_hce_ahrs_report_month_decode(uint8_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_month_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 12u));
}

uint8_t ahrs_hce_ahrs_report_day_encode(float value)
{
    return (uint8_t)(value);
}

float ahrs_hce_ahrs_report_day_decode(uint8_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_day_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 31u));
}

uint8_t ahrs_hce_ahrs_report_hour_encode(float value)
{
    return (uint8_t)(value);
}

float ahrs_hce_ahrs_report_hour_decode(uint8_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_hour_is_in_range(uint8_t value)
{
    return (value <= 23u);
}

uint8_t ahrs_hce_ahrs_report_minute_encode(float value)
{
    return (uint8_t)(value);
}

float ahrs_hce_ahrs_report_minute_decode(uint8_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_minute_is_in_range(uint8_t value)
{
    return (value <= 59u);
}

uint16_t ahrs_hce_ahrs_report_millisecond_encode(float value)
{
    return (uint16_t)(value);
}

float ahrs_hce_ahrs_report_millisecond_decode(uint16_t value)
{
    return ((float)value);
}

bool ahrs_hce_ahrs_report_millisecond_is_in_range(uint16_t value)
{
    return (value <= 999u);
}
