/**
 * @file ahrs.h
 *
 * @brief This header file was generated by cantools version 40.5.0 Fri Mar 27 15:50:15 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef AHRS_H
#define AHRS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define AHRS_HCE_AHRS_REPORT_FRAME_ID (0x10000u)

/* Frame lengths in bytes. */
#define AHRS_HCE_AHRS_REPORT_LENGTH (64u)

/* Extended or standard frame types. */
#define AHRS_HCE_AHRS_REPORT_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define AHRS_HCE_AHRS_REPORT_SYSTEM_STATUS_OK_CHOICE (170u)

/* Frame Names. */
#define AHRS_HCE_AHRS_REPORT_NAME "HCE_AHRS_Report"

/* Signal Names. */
#define AHRS_HCE_AHRS_REPORT_SYSTEM_STATUS_NAME "SystemStatus"
#define AHRS_HCE_AHRS_REPORT_PITCH_NAME "Pitch"
#define AHRS_HCE_AHRS_REPORT_ROLL_NAME "Roll"
#define AHRS_HCE_AHRS_REPORT_YAW_NAME "Yaw"
#define AHRS_HCE_AHRS_REPORT_ACCEL_X_NAME "AccelX"
#define AHRS_HCE_AHRS_REPORT_ACCEL_Y_NAME "AccelY"
#define AHRS_HCE_AHRS_REPORT_ACCEL_Z_NAME "AccelZ"
#define AHRS_HCE_AHRS_REPORT_ANG_VEL_PITCH_NAME "AngVelPitch"
#define AHRS_HCE_AHRS_REPORT_ANG_VEL_ROLL_NAME "AngVelRoll"
#define AHRS_HCE_AHRS_REPORT_ANG_VEL_YAW_NAME "AngVelYaw"
#define AHRS_HCE_AHRS_REPORT_PRESSURE_ALTITUDE_NAME "PressureAltitude"
#define AHRS_HCE_AHRS_REPORT_OAT_NAME "OAT"
#define AHRS_HCE_AHRS_REPORT_LATITUDE_NAME "Latitude"
#define AHRS_HCE_AHRS_REPORT_LONGITUDE_NAME "Longitude"
#define AHRS_HCE_AHRS_REPORT_NUM_SAT_NAME "NumSat"
#define AHRS_HCE_AHRS_REPORT_YEAR_NAME "Year"
#define AHRS_HCE_AHRS_REPORT_MONTH_NAME "Month"
#define AHRS_HCE_AHRS_REPORT_DAY_NAME "Day"
#define AHRS_HCE_AHRS_REPORT_HOUR_NAME "Hour"
#define AHRS_HCE_AHRS_REPORT_MINUTE_NAME "Minute"
#define AHRS_HCE_AHRS_REPORT_MILLISECOND_NAME "Millisecond"

/**
 * Signals in message HCE_AHRS_Report.
 *
 * AHRS Periodic Report Message (FDCAN)
 *
 * All signal values are as on the CAN bus.
 */
struct ahrs_hce_ahrs_report_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t system_status;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t pitch;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t roll;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 deg)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t yaw;

    /**
     * Range: -32768..32767 (-32.768..32.767 G)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 G)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 G)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_z;

    /**
     * Range: -32768..32767 (-32.768..32.767 deg/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t ang_vel_pitch;

    /**
     * Range: -32768..32767 (-32.768..32.767 deg/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t ang_vel_roll;

    /**
     * Range: -32768..32767 (-32.768..32.767 deg/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t ang_vel_yaw;

    /**
     * Range: 0..65535 (0..65535 ft)
     * Scale: 1
     * Offset: 0
     */
    uint16_t pressure_altitude;

    /**
     * Range: -128..127 (-128..127 C)
     * Scale: 1
     * Offset: 0
     */
    int8_t oat;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float latitude;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    float longitude;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t num_sat;

    /**
     * Range: 0..255 (2000..2255 year)
     * Scale: 1
     * Offset: 2000
     */
    uint8_t year;

    /**
     * Range: 1..12 (1..12 month)
     * Scale: 1
     * Offset: 0
     */
    uint8_t month;

    /**
     * Range: 1..31 (1..31 day)
     * Scale: 1
     * Offset: 0
     */
    uint8_t day;

    /**
     * Range: 0..23 (0..23 h)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hour;

    /**
     * Range: 0..59 (0..59 m)
     * Scale: 1
     * Offset: 0
     */
    uint8_t minute;

    /**
     * Range: 0..999 (0..999 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t millisecond;
};

/**
 * Pack message HCE_AHRS_Report.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ahrs_hce_ahrs_report_pack(
    uint8_t *dst_p,
    const struct ahrs_hce_ahrs_report_t *src_p,
    size_t size);

/**
 * Unpack message HCE_AHRS_Report.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ahrs_hce_ahrs_report_unpack(
    struct ahrs_hce_ahrs_report_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HCE_AHRS_Report.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ahrs_hce_ahrs_report_init(struct ahrs_hce_ahrs_report_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ahrs_hce_ahrs_report_system_status_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_system_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_system_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_pitch_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_pitch_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_pitch_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_roll_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_roll_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_roll_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_yaw_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_yaw_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_yaw_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_accel_x_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_accel_y_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_accel_z_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_accel_z_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_ang_vel_pitch_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_ang_vel_pitch_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_ang_vel_pitch_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_ang_vel_roll_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_ang_vel_roll_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_ang_vel_roll_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t ahrs_hce_ahrs_report_ang_vel_yaw_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_ang_vel_yaw_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_ang_vel_yaw_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ahrs_hce_ahrs_report_pressure_altitude_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_pressure_altitude_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_pressure_altitude_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t ahrs_hce_ahrs_report_oat_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_oat_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_oat_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float ahrs_hce_ahrs_report_latitude_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_latitude_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_latitude_is_in_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float ahrs_hce_ahrs_report_longitude_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_longitude_decode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_longitude_is_in_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ahrs_hce_ahrs_report_num_sat_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_num_sat_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_num_sat_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ahrs_hce_ahrs_report_year_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_year_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_year_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ahrs_hce_ahrs_report_month_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_month_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_month_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ahrs_hce_ahrs_report_day_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_day_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_day_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ahrs_hce_ahrs_report_hour_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_hour_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_hour_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t ahrs_hce_ahrs_report_minute_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_minute_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_minute_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t ahrs_hce_ahrs_report_millisecond_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float ahrs_hce_ahrs_report_millisecond_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool ahrs_hce_ahrs_report_millisecond_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
