/**
 * @file hce.c
 *
 * @brief This source file was generated by cantools version 40.5.0 Fri Mar 27 15:50:23 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "can_hce.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int hce_hce_alt_radar_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_alt_radar_report_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->agl, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->agl, 0u, 0xffu);

    return (2);
}

int hce_hce_alt_radar_report_unpack(
    struct hce_hce_alt_radar_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->agl = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->agl |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int hce_hce_alt_radar_report_init(struct hce_hce_alt_radar_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_alt_radar_report_t));

    return 0;
}

uint16_t hce_hce_alt_radar_report_agl_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float hce_hce_alt_radar_report_agl_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool hce_hce_alt_radar_report_agl_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_emu_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_emu_report_t *src_p,
    size_t size)
{
    uint8_t icurrent;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->vbatt, 0u, 0xffu);
    icurrent = (uint8_t)src_p->icurrent;
    dst_p[1] |= pack_left_shift_u8(icurrent, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rotor_rpm, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->rotor_rpm, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->motor_rpm, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->motor_rpm, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->egt, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->egt, 0u, 0xffu);

    return (8);
}

int hce_hce_emu_report_unpack(
    struct hce_hce_emu_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t icurrent;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vbatt = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    icurrent = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->icurrent = (int8_t)icurrent;
    dst_p->rotor_rpm = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->rotor_rpm |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->motor_rpm = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->motor_rpm |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->egt = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->egt |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int hce_hce_emu_report_init(struct hce_hce_emu_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_emu_report_t));

    return 0;
}

uint8_t hce_hce_emu_report_vbatt_encode(float value)
{
    return (uint8_t)(value / 0.1f);
}

float hce_hce_emu_report_vbatt_decode(uint8_t value)
{
    return ((float)value * 0.1f);
}

bool hce_hce_emu_report_vbatt_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int8_t hce_hce_emu_report_icurrent_encode(float value)
{
    return (int8_t)(value);
}

float hce_hce_emu_report_icurrent_decode(int8_t value)
{
    return ((float)value);
}

bool hce_hce_emu_report_icurrent_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

uint16_t hce_hce_emu_report_rotor_rpm_encode(float value)
{
    return (uint16_t)(value);
}

float hce_hce_emu_report_rotor_rpm_decode(uint16_t value)
{
    return ((float)value);
}

bool hce_hce_emu_report_rotor_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t hce_hce_emu_report_motor_rpm_encode(float value)
{
    return (uint16_t)(value);
}

float hce_hce_emu_report_motor_rpm_decode(uint16_t value)
{
    return ((float)value);
}

bool hce_hce_emu_report_motor_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t hce_hce_emu_report_egt_encode(float value)
{
    return (uint16_t)(value);
}

float hce_hce_emu_report_egt_decode(uint16_t value)
{
    return ((float)value);
}

bool hce_hce_emu_report_egt_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_cyclic_x_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_x_report_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint16_t)src_p->position;
    dst_p[2] |= pack_right_shift_u16(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(position, 0u, 0xffu);

    return (8);
}

int hce_hce_ssdm_cyclic_x_report_unpack(
    struct hce_hce_ssdm_cyclic_x_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->position = (int16_t)position;

    return (0);
}

int hce_hce_ssdm_cyclic_x_report_init(struct hce_hce_ssdm_cyclic_x_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_cyclic_x_report_t));

    return 0;
}

int16_t hce_hce_ssdm_cyclic_x_report_position_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_cyclic_x_report_position_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_cyclic_x_report_position_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_cyclic_x_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_x_set_position_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    setpoint = (uint16_t)src_p->setpoint;
    dst_p[0] |= pack_right_shift_u16(setpoint, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(setpoint, 0u, 0xffu);

    return (2);
}

int hce_hce_ssdm_cyclic_x_set_position_unpack(
    struct hce_hce_ssdm_cyclic_x_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    setpoint = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    setpoint |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->setpoint = (int16_t)setpoint;

    return (0);
}

int hce_hce_ssdm_cyclic_x_set_position_init(struct hce_hce_ssdm_cyclic_x_set_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_cyclic_x_set_position_t));

    return 0;
}

int16_t hce_hce_ssdm_cyclic_x_set_position_setpoint_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_cyclic_x_set_position_setpoint_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_cyclic_x_set_position_setpoint_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_cyclic_y_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_y_report_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint16_t)src_p->position;
    dst_p[2] |= pack_right_shift_u16(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(position, 0u, 0xffu);

    return (8);
}

int hce_hce_ssdm_cyclic_y_report_unpack(
    struct hce_hce_ssdm_cyclic_y_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->position = (int16_t)position;

    return (0);
}

int hce_hce_ssdm_cyclic_y_report_init(struct hce_hce_ssdm_cyclic_y_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_cyclic_y_report_t));

    return 0;
}

int16_t hce_hce_ssdm_cyclic_y_report_position_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_cyclic_y_report_position_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_cyclic_y_report_position_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_cyclic_y_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_cyclic_y_set_position_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    setpoint = (uint16_t)src_p->setpoint;
    dst_p[0] |= pack_right_shift_u16(setpoint, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(setpoint, 0u, 0xffu);

    return (2);
}

int hce_hce_ssdm_cyclic_y_set_position_unpack(
    struct hce_hce_ssdm_cyclic_y_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    setpoint = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    setpoint |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->setpoint = (int16_t)setpoint;

    return (0);
}

int hce_hce_ssdm_cyclic_y_set_position_init(struct hce_hce_ssdm_cyclic_y_set_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_cyclic_y_set_position_t));

    return 0;
}

int16_t hce_hce_ssdm_cyclic_y_set_position_setpoint_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_cyclic_y_set_position_setpoint_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_cyclic_y_set_position_setpoint_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_collective_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_collective_report_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint16_t)src_p->position;
    dst_p[2] |= pack_right_shift_u16(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(position, 0u, 0xffu);

    return (8);
}

int hce_hce_ssdm_collective_report_unpack(
    struct hce_hce_ssdm_collective_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->position = (int16_t)position;

    return (0);
}

int hce_hce_ssdm_collective_report_init(struct hce_hce_ssdm_collective_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_collective_report_t));

    return 0;
}

int16_t hce_hce_ssdm_collective_report_position_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_collective_report_position_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_collective_report_position_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_collective_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_collective_set_position_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    setpoint = (uint16_t)src_p->setpoint;
    dst_p[0] |= pack_right_shift_u16(setpoint, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(setpoint, 0u, 0xffu);

    return (2);
}

int hce_hce_ssdm_collective_set_position_unpack(
    struct hce_hce_ssdm_collective_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    setpoint = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    setpoint |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->setpoint = (int16_t)setpoint;

    return (0);
}

int hce_hce_ssdm_collective_set_position_init(struct hce_hce_ssdm_collective_set_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_collective_set_position_t));

    return 0;
}

int16_t hce_hce_ssdm_collective_set_position_setpoint_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_collective_set_position_setpoint_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_collective_set_position_setpoint_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_rudder_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_rudder_report_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint16_t)src_p->position;
    dst_p[2] |= pack_right_shift_u16(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(position, 0u, 0xffu);

    return (8);
}

int hce_hce_ssdm_rudder_report_unpack(
    struct hce_hce_ssdm_rudder_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->position = (int16_t)position;

    return (0);
}

int hce_hce_ssdm_rudder_report_init(struct hce_hce_ssdm_rudder_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_rudder_report_t));

    return 0;
}

int16_t hce_hce_ssdm_rudder_report_position_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_rudder_report_position_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_rudder_report_position_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_rudder_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_rudder_set_position_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    setpoint = (uint16_t)src_p->setpoint;
    dst_p[0] |= pack_right_shift_u16(setpoint, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(setpoint, 0u, 0xffu);

    return (2);
}

int hce_hce_ssdm_rudder_set_position_unpack(
    struct hce_hce_ssdm_rudder_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    setpoint = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    setpoint |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->setpoint = (int16_t)setpoint;

    return (0);
}

int hce_hce_ssdm_rudder_set_position_init(struct hce_hce_ssdm_rudder_set_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_rudder_set_position_t));

    return 0;
}

int16_t hce_hce_ssdm_rudder_set_position_setpoint_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_rudder_set_position_setpoint_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_rudder_set_position_setpoint_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_throttle_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_throttle_report_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint16_t)src_p->position;
    dst_p[2] |= pack_right_shift_u16(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(position, 0u, 0xffu);

    return (8);
}

int hce_hce_ssdm_throttle_report_unpack(
    struct hce_hce_ssdm_throttle_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->position = (int16_t)position;

    return (0);
}

int hce_hce_ssdm_throttle_report_init(struct hce_hce_ssdm_throttle_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_throttle_report_t));

    return 0;
}

int16_t hce_hce_ssdm_throttle_report_position_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_throttle_report_position_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_throttle_report_position_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_throttle_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_throttle_set_position_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    setpoint = (uint16_t)src_p->setpoint;
    dst_p[0] |= pack_right_shift_u16(setpoint, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(setpoint, 0u, 0xffu);

    return (2);
}

int hce_hce_ssdm_throttle_set_position_unpack(
    struct hce_hce_ssdm_throttle_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    setpoint = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    setpoint |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->setpoint = (int16_t)setpoint;

    return (0);
}

int hce_hce_ssdm_throttle_set_position_init(struct hce_hce_ssdm_throttle_set_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_throttle_set_position_t));

    return 0;
}

int16_t hce_hce_ssdm_throttle_set_position_setpoint_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_throttle_set_position_setpoint_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_throttle_set_position_setpoint_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_auxiliary_report_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_auxiliary_report_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    position = (uint16_t)src_p->position;
    dst_p[2] |= pack_right_shift_u16(position, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(position, 0u, 0xffu);

    return (8);
}

int hce_hce_ssdm_auxiliary_report_unpack(
    struct hce_hce_ssdm_auxiliary_report_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t position;

    if (size < 8u) {
        return (-EINVAL);
    }

    position = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    position |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->position = (int16_t)position;

    return (0);
}

int hce_hce_ssdm_auxiliary_report_init(struct hce_hce_ssdm_auxiliary_report_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_auxiliary_report_t));

    return 0;
}

int16_t hce_hce_ssdm_auxiliary_report_position_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_auxiliary_report_position_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_auxiliary_report_position_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int hce_hce_ssdm_auxiliary_set_position_pack(
    uint8_t *dst_p,
    const struct hce_hce_ssdm_auxiliary_set_position_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    setpoint = (uint16_t)src_p->setpoint;
    dst_p[0] |= pack_right_shift_u16(setpoint, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(setpoint, 0u, 0xffu);

    return (2);
}

int hce_hce_ssdm_auxiliary_set_position_unpack(
    struct hce_hce_ssdm_auxiliary_set_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint;

    if (size < 2u) {
        return (-EINVAL);
    }

    setpoint = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    setpoint |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->setpoint = (int16_t)setpoint;

    return (0);
}

int hce_hce_ssdm_auxiliary_set_position_init(struct hce_hce_ssdm_auxiliary_set_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct hce_hce_ssdm_auxiliary_set_position_t));

    return 0;
}

int16_t hce_hce_ssdm_auxiliary_set_position_setpoint_encode(float value)
{
    return (int16_t)(value / 3.0517578125e-05f);
}

float hce_hce_ssdm_auxiliary_set_position_setpoint_decode(int16_t value)
{
    return ((float)value * 3.0517578125e-05f);
}

bool hce_hce_ssdm_auxiliary_set_position_setpoint_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
